version: '3.8'

volumes:
  postgres_volume:

services:
  postgres:
    build: infra/postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  php:
    build: ./infra/php
    depends_on:
      - postgres
    volumes:
      - ./src:/var/www/html
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "jimmy"
      XDEBUG_CONFIG: "mode=debug client_host=172.17.0.1 client_port=9003 idekey=jimmy start_with_request=yes"
      PHP_IDE_CONFIG: "serverName=jimmy"

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./src/swagger/openapi.yaml:/swagger.yaml
    ports:
      - 8080:8080
    environment:
      SWAGGER_JSON: "/swagger.yaml"

  nginx:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/nginx/cors.conf:/etc/nginx/conf.d/cors.conf
